// VibeShip Main JavaScript

// Product data cache
let products = [];
let currentCategory = 'all';
let searchQuery = '';

// Social media icon mapping
const socialIcons = {
  // Known platforms
  'github': '/icons/github.svg',
  'twitter': '/icons/twitter.svg',
  'x.com': '/icons/twitter.svg',
  'weibo': '/icons/weibo.svg',
  'xiaohongshu': '/icons/xiaohongshu.svg',
  '小红书': '/icons/xiaohongshu.svg',
  'zhihu': '/icons/zhihu.svg',
  '知乎': '/icons/zhihu.svg',
  'bilibili': '/icons/bilibili.svg',
  'b站': '/icons/bilibili.svg',
  'juejin': '/icons/juejin.svg',
  '掘金': '/icons/juejin.svg',
  'csdn': '/icons/csdn.svg',
  'douyin': '/icons/douyin.svg',
  '抖音': '/icons/douyin.svg',
  'wechat': '/icons/wechat.svg',
  '微信': '/icons/wechat.svg',
  'email': '/icons/email.svg',
  'mail': '/icons/email.svg',
};

// Get social icon URL based on URL or platform name
function getSocialIcon(url) {
  if (!url) return '/icons/default.svg';

  const lowerUrl = url.toLowerCase();

  // Check domain patterns
  const patterns = [
    { pattern: 'github.com', icon: '/icons/github.svg' },
    { pattern: 'twitter.com', icon: '/icons/twitter.svg' },
    { pattern: 'x.com', icon: '/icons/twitter.svg' },
    { pattern: 'weibo.com', icon: '/icons/weibo.svg' },
    { pattern: 'xiaohongshu.com', icon: '/icons/xiaohongshu.svg' },
    { pattern: 'zhihu.com', icon: '/icons/zhihu.svg' },
    { pattern: 'bilibili.com', icon: '/icons/bilibili.svg' },
    { pattern: 'juejin.cn', icon: '/icons/juejin.svg' },
    { pattern: 'csdn.net', icon: '/icons/csdn.svg' },
    { pattern: 'douyin.com', icon: '/icons/douyin.svg' },
    { pattern: 'tiktok.com', icon: '/icons/douyin.svg' },
    { pattern: 'wechat.com', icon: '/icons/wechat.svg' },
    { pattern: 'mp.weixin.qq.com', icon: '/icons/wechat.svg' },
  ];

  for (const p of patterns) {
    if (lowerUrl.includes(p.pattern)) {
      return p.icon;
    }
  }

  // Check for email
  if (lowerUrl.startsWith('mailto:') || lowerUrl.includes('@')) {
    return '/icons/email.svg';
  }

  return '/icons/default.svg';
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
  // Only run on home page
  if (document.getElementById('productGrid')) {
    initHomePage();
  }
});

async function initHomePage() {
  // Load products
  await loadProducts();

  // Setup event listeners
  setupSearch();
  setupCategoryFilter();

  // Initial render
  renderProducts();
}

async function loadProducts() {
  try {
    // Load products index
    const response = await fetch('/products/products.json');
    if (response.ok) {
      const data = await response.json();
      products = data.products || [];
    } else {
      // Fallback: try to load each product directory
      products = await discoverProducts();
    }
  } catch (error) {
    console.error('Error loading products:', error);
    products = [];
  }

  // Sort by date (newest first) - assume directory order or filename
  products.sort((a, b) => {
    const dateA = new Date(a.submittedAt || 0);
    const dateB = new Date(b.submittedAt || 0);
    return dateB - dateA;
  });
}

async function discoverProducts() {
  // This is a fallback - in production, products.json would be generated by the build script
  return [];
}

function normalizeExternalUrl(url) {
  if (typeof url !== 'string') return '';
  const trimmed = url.trim();
  if (!trimmed) return '';

  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      return '';
    }
    return parsed.toString();
  } catch (error) {
    return '';
  }
}

function normalizeEmail(email) {
  if (typeof email !== 'string') return '';
  const trimmed = email.trim();
  if (!trimmed) return '';
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(trimmed) ? trimmed : '';
}

function sanitizePathSegment(segment) {
  if (typeof segment !== 'string') return '';
  const trimmed = segment.trim();
  if (!trimmed) return '';
  return /^[a-zA-Z0-9._-]+$/.test(trimmed) ? trimmed : '';
}

function buildProductAssetUrl(productId, assetName) {
  const safeProductId = sanitizePathSegment(productId);
  const safeAssetName = sanitizePathSegment(assetName);
  if (!safeProductId || !safeAssetName) return '';
  return `/products/${encodeURIComponent(safeProductId)}/${encodeURIComponent(safeAssetName)}`;
}

function setupSearch() {
  const searchInput = document.getElementById('searchInput');
  if (!searchInput) return;

  let debounceTimer;
  searchInput.addEventListener('input', (e) => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      searchQuery = e.target.value.toLowerCase().trim();
      renderProducts();
    }, 300);
  });
}

function setupCategoryFilter() {
  const filterContainer = document.getElementById('categoryFilter');
  if (!filterContainer) return;

  filterContainer.addEventListener('click', (e) => {
    const pill = e.target.closest('.category-pill');
    if (!pill) return;

    // Update active state
    filterContainer.querySelectorAll('.category-pill').forEach(p => p.classList.remove('active'));
    pill.classList.add('active');

    // Update filter
    currentCategory = pill.dataset.category;
    renderProducts();
  });
}

function filterProducts() {
  return products.filter(product => {
    // Category filter
    if (currentCategory !== 'all' && product.category !== currentCategory) {
      return false;
    }

    // Search filter
    if (searchQuery) {
      const searchableText = [
        product.name,
        product.tagline,
        product.description,
        ...(product.tags || []),
        product.category
      ].join(' ').toLowerCase();

      if (!searchableText.includes(searchQuery)) {
        return false;
      }
    }

    return true;
  });
}

function renderProducts() {
  const grid = document.getElementById('productGrid');
  const emptyState = document.getElementById('emptyState');

  if (!grid) return;

  const filtered = filterProducts();

  if (filtered.length === 0) {
    grid.innerHTML = '';
    emptyState.style.display = 'block';
    return;
  }

  emptyState.style.display = 'none';

  grid.innerHTML = filtered.map(product => createProductCard(product)).join('');

  // Add click handlers
  grid.querySelectorAll('.product-card').forEach(card => {
    card.addEventListener('click', () => {
      window.location.href = `/product/?id=${card.dataset.id}`;
    });
  });
}

function createProductCard(product) {
  const screenshotUrl = Array.isArray(product.screenshots) && product.screenshots[0]
    ? (buildProductAssetUrl(product.id, product.screenshots[0]) || 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 9"%3E%3Crect fill="%23E0E7FF" width="16" height="9"/%3E%3C/svg%3E')
    : 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 9"%3E%3Crect fill="%23E0E7FF" width="16" height="9"/%3E%3C/svg%3E';

  const fallbackAvatar = `https://ui-avatars.com/api/?name=${encodeURIComponent(product.author?.name || 'U')}&background=E0E7FF&color=6366F1&size=40`;
  const safeProductId = sanitizePathSegment(product.id);

  return `
    <article class="product-card" data-id="${escapeHtml(safeProductId)}">
      <div class="product-screenshot">
        <img src="${screenshotUrl}" alt="${escapeHtml(product.name)}" loading="lazy">
      </div>
      <div class="product-content">
        <h3 class="product-name">${escapeHtml(product.name)}</h3>
        <p class="product-tagline">${escapeHtml(product.tagline)}</p>
        <div class="product-meta">
          <span class="product-category">${escapeHtml(product.category)}</span>
          ${product.author ? `
            <div class="product-author">
              <img src="${fallbackAvatar}" alt="${escapeHtml(product.author.name)}">
              <span>${escapeHtml(product.author.name)}</span>
            </div>
          ` : ''}
        </div>
        <div class="product-contacts">
          ${renderContactIcons(product.contact)}
        </div>
      </div>
    </article>
  `;
}

function renderContactIcons(contact) {
  if (!contact || typeof contact !== 'object') return '';

  let html = '';
  const safeGithub = normalizeExternalUrl(contact.github);
  const safeTwitter = normalizeExternalUrl(contact.twitter);
  const safeEmail = normalizeEmail(contact.email);

  if (safeGithub) {
    html += `<a href="${escapeHtml(safeGithub)}" class="contact-icon-link" target="_blank" rel="noopener noreferrer" title="GitHub">
      <img src="${getSocialIcon(safeGithub)}" alt="GitHub" class="contact-icon">
    </a>`;
  }

  if (safeTwitter) {
    html += `<a href="${escapeHtml(safeTwitter)}" class="contact-icon-link" target="_blank" rel="noopener noreferrer" title="Twitter">
      <img src="${getSocialIcon(safeTwitter)}" alt="Twitter" class="contact-icon">
    </a>`;
  }

  if (safeEmail) {
    const safeMailto = `mailto:${encodeURIComponent(safeEmail)}`;
    html += `<a href="${safeMailto}" class="contact-icon-link" title="Email">
      <img src="${getSocialIcon(safeEmail)}" alt="Email" class="contact-icon">
    </a>`;
  }

  // Render other contact fields dynamically
  const skipFields = ['github', 'twitter', 'email'];
  for (const [key, value] of Object.entries(contact)) {
    if (skipFields.includes(key)) continue;
    const safeUrl = normalizeExternalUrl(value);
    if (safeUrl) {
      html += `<a href="${escapeHtml(safeUrl)}" class="contact-icon-link" target="_blank" rel="noopener noreferrer" title="${escapeHtml(key)}">
        <img src="${getSocialIcon(safeUrl)}" alt="${escapeHtml(key)}" class="contact-icon">
      </a>`;
    }
  }

  return html;
}

function escapeHtml(text) {
  if (!text) return '';
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

// Export utility for other pages.
window.getSocialIcon = getSocialIcon;
